<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Card;
use Illuminate\Support\Facades\Hash;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Card::create([ 'name' => 'ＩＴストラテジスト ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '71', 'rank' => 'S' ]);
        Card::create([ 'name' => 'システム監査技術者  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '70', 'rank' => 'S' ]);
        Card::create([ 'name' => 'プロジェクトマネージャー  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '69', 'rank' => 'A' ]);
        Card::create([ 'name' => 'システムアーキテクト ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ＩＴサービスマネージャ ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => '情報セキュリティスペシャリスト ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ネットワークスペシャリスト ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'データベーススペシャリスト', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'エンベデッドシステムスペシャリスト ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'CCNP ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => '応用情報技術者 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ディジタル技術検定 １級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => 'オラクルマスターゴールド ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => 'PMP試験 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '64', 'rank' => 'A' ]);
        Card::create([ 'name' => 'XMLマスター ：プロフェッショナル ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '64', 'rank' => 'A' ]);
        Card::create([ 'name' => 'SUN技術者認定資格 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '62', 'rank' => 'A' ]);
        Card::create([ 'name' => 'MCP (上位資格)  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '57', 'rank' => 'B' ]);
        Card::create([ 'name' => 'CG-ARTS検定(CGエンジニア検定 エキスパート） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => 'パソコン検定（Ｐ検） １級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => 'パソコン整備士１級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ディジタル技術検定 ２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ウェブデザイン技能検定 ２級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ITコーディネータ ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'オラクルマスターシルバー ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'QuarkXPressクリエイター能力認定試験 １級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => 'Linux（LPIＣレベル２） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => 'マルチメディア検定（エキスパート） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '52', 'rank' => 'B' ]);
        Card::create([ 'name' => 'VBAエキスパート （スタンダード） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '52', 'rank' => 'B' ]);
        Card::create([ 'name' => 'CAD利用技術者試験 １級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '52', 'rank' => 'B' ]);
        Card::create([ 'name' => '情報セキュリティ管理士認定試験  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => '.com Master ダブルスター ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => 'MCPC モバイルシステム技術検定 １級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => '基本情報技術者試験 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => '情報処理技術者能力認定試験 １級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => 'C言語プログラミング能力検定試験 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ＥＣ(電子商取引)実践能力検定 ２級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '49', 'rank' => 'C' ]);
        Card::create([ 'name' => 'CG-ARTS検定 (ベーシック) ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '48', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ソフトウェア品質技術者中級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '48', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報処理技術者能力認定試験 ２級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報処理技術者能力認定試験 ３級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => 'CIW ファンデーション（Web Foundations Associate） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => 'XMLマスター ：ベーシック  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ウェブデザイン技能検定 ３級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => '文書情報管理士１級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'パソコン検定（Ｐ検）２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ソフトウェア品質技術者初級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'MCP(基本資格) ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ITパスポート試験 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報活用試験（J検） １級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報検索応用能力試験 ２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ディジタル技術検定 ３級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報システム試験（J検） ＳＥ認定/ＰＧ認定 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'CADトレース技能審査 初級・中級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'IT検証技術者認定試験 エントリーレベル１と２ ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'JSTQB認定テスト技術者資格認定試験 Foundation Level ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報セキュリティ初級認定試験  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '電子メール活用能力検定 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'Turbolinux技術者認定試験 Turbo-CE ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'VBAエキスパート （ベーシック） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '文書情報管理士２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '44', 'rank' => 'C' ]);
        Card::create([ 'name' => 'Web検定', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '44', 'rank' => 'C' ]);
        Card::create([ 'name' => 'パソコン整備士２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '44', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ＥＣ(電子商取引)実践能力検定 ３級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報活用試験（J検）２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => 'MCPC モバイルシステム技術検定 ２級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => '情報デザイン試験（J検） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '42', 'rank' => 'C' ]);
        Card::create([ 'name' => 'Linux（LPIＣレベル１） ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '42', 'rank' => 'C' ]);
        Card::create([ 'name' => '.com Master シングルスター ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '42', 'rank' => 'C' ]);
        Card::create([ 'name' => 'CAD利用技術者試験 ２級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '42', 'rank' => 'C' ]);
        Card::create([ 'name' => '文書デザイン検定 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '39', 'rank' => 'D' ]);
        Card::create([ 'name' => '情報活用試験（J検）３級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '39', 'rank' => 'D' ]);
        Card::create([ 'name' => '日商ＰＣ検定 ３級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '39', 'rank' => 'D' ]);
        Card::create([ 'name' => 'マイクロソフト オフィススペシャリストマスター ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => 'パソコン検定（Ｐ検）３級 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => 'MCPCケータイ実務検定 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => '情報検索基礎能力試験 ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '37', 'rank' => 'D' ]);
        Card::create([ 'name' => 'Word/Excel文書処理技能認定試験３級  ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '37', 'rank' => 'D' ]);
        Card::create([ 'name' => 'MOS（スペッシャリスト）   ', 'description' => '', 'type' => 'IT・パソコン・情報技術', 'power' => '37', 'rank' => 'D' ]);
        Card::create([ 'name' => '中国語検定1級 ', 'description' => '', 'type' => '語学・言語', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => '実用イタリア語検定 １級 ', 'description' => '', 'type' => '語学・言語', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => '翻訳実務検定TQE ', 'description' => '', 'type' => '語学・言語', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => 'JTA公認翻訳専門職資格試験 ', 'description' => '', 'type' => '語学・言語', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ドイツ語技能検定 １級 ', 'description' => '', 'type' => '語学・言語', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ほんやく検定（JTF） 実用レベル２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ハングル能力検定試験 ２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => '知的財産翻訳検定 １級 ', 'description' => '', 'type' => '語学・言語', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => 'グレッグ英文速記公式検定 ', 'description' => '', 'type' => '語学・言語', 'power' => '64', 'rank' => 'A' ]);
        Card::create([ 'name' => '実用英語技能検定1級 ', 'description' => '', 'type' => '語学・言語', 'power' => '64', 'rank' => 'A' ]);
        Card::create([ 'name' => '国際英検G-TELP レベル1', 'description' => '', 'type' => '語学・言語', 'power' => '64', 'rank' => 'A' ]);
        Card::create([ 'name' => '通訳案内士 ', 'description' => '', 'type' => '語学・言語', 'power' => '63', 'rank' => 'A' ]);
        Card::create([ 'name' => '実用英語技能検定準1級 ', 'description' => '', 'type' => '語学・言語', 'power' => '59', 'rank' => 'B' ]);
        Card::create([ 'name' => '中日通検 ', 'description' => '', 'type' => '語学・言語', 'power' => '58', 'rank' => 'B' ]);
        Card::create([ 'name' => 'TOEIC TEST７００点 ', 'description' => '', 'type' => '語学・言語', 'power' => '57', 'rank' => 'B' ]);
        Card::create([ 'name' => 'スペイン語技能検定 ３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '56', 'rank' => 'B' ]);
        Card::create([ 'name' => '実用イタリア語検定 ３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '56', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ドイツ語技能検定 準１級   ', 'description' => '', 'type' => '語学・言語', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ほんやく検定（JTF） 実用レベル３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '中国語検定試験 ２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '実用フランス語検定 ２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '国際英検G-TELP レベル２ ', 'description' => '', 'type' => '語学・言語', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '日本語能力試験(JLPT)N３  ', 'description' => '', 'type' => '語学・言語', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => '知的財産翻訳検定 ２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => '中国語検定試験３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '46', 'rank' => 'C' ]);
        Card::create([ 'name' => '実用英語検定（英検）２級 ', 'description' => '', 'type' => '語学・言語', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ハングル能力検定試験 ３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '実用イタリア語検定４級・５級 ', 'description' => '', 'type' => '語学・言語', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '国際英検G-TELP レベル３ ', 'description' => '', 'type' => '語学・言語', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '漢字検定 ３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '39', 'rank' => 'D' ]);
        Card::create([ 'name' => '国際英検G-TELP レベル4 ', 'description' => '', 'type' => '語学・言語', 'power' => '39', 'rank' => 'D' ]);
        Card::create([ 'name' => 'スペイン語技能検定 ６級 ', 'description' => '', 'type' => '語学・言語', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => '実用英語検定（英検）３級 ', 'description' => '', 'type' => '語学・言語', 'power' => '36', 'rank' => 'D' ]);
        Card::create([ 'name' => '公認会計士  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '75', 'rank' => 'S' ]);
        Card::create([ 'name' => 'ＭＢＡ（経営学修士） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '69', 'rank' => 'A' ]);
        Card::create([ 'name' => '税理士', 'description' => '', 'type' => 'ビジネス関連', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => 'アクチュアリー ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '68', 'rank' => 'A' ]);
        Card::create([ 'name' => '国際会計検定（BATIC） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '67', 'rank' => 'A' ]);
        Card::create([ 'name' => '中小企業診断士  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '66', 'rank' => 'A' ]);
        Card::create([ 'name' => 'CFA協会認定証券アナリスト ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '65', 'rank' => 'A' ]);
        Card::create([ 'name' => '証券アナリスト( CMA) ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '62', 'rank' => 'A' ]);
        Card::create([ 'name' => '農業協同組合監査士  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '62', 'rank' => 'A' ]);
        Card::create([ 'name' => '公認内部監査人（CIA） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '60', 'rank' => 'A' ]);
        Card::create([ 'name' => 'ＣＦＰ / FP技能士１級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '58', 'rank' => 'B' ]);
        Card::create([ 'name' => '金融窓口サービス技能検定 １級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '証券外務員 １種 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ビジネス能力検定試験（Ｂ検）１級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '55', 'rank' => 'B' ]);
        Card::create([ 'name' => '販売士１級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ＰＲプランナー ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '54', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ディスクロージャー経理実務検定（基礎編） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => 'IFRS検定（国際会計基準検定） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => '日商簿記検定２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => '金融窓口サービス技能検定 ２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ビジネス会計検定 ２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => '銀行業務検定 ２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => 'SC経営士 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '53', 'rank' => 'B' ]);
        Card::create([ 'name' => '経営学検定中級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '52', 'rank' => 'B' ]);
        Card::create([ 'name' => 'マーケティング・ビジネス実務検定 Ｂ級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '52', 'rank' => 'B' ]);
        Card::create([ 'name' => '会計ソフト実務能力試験 1級(旧PC財務関係主任者) ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => '税務会計能力検定１級（税務会計検定）  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => '電子化ファイリング検定 Ａ級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => '電卓技能検定試験 １級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '51', 'rank' => 'B' ]);
        Card::create([ 'name' => 'DCプランナー１級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => 'ビジネス・キャリア検定試験 ２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => 'プロフェッショナル CFO ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '50', 'rank' => 'B' ]);
        Card::create([ 'name' => '貸金業務取扱主任者  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '49', 'rank' => 'C' ]);
        Card::create([ 'name' => '銀行業務検定 ３級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '48', 'rank' => 'C' ]);
        Card::create([ 'name' => 'DCアドバイザー ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => 'スタンダード CFO ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => 'FASS(経理・財務スキル検定)レベルC ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '47', 'rank' => 'C' ]);
        Card::create([ 'name' => '電子化ファイリング検定 Ｂ級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '販売士２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '日商簿記検定 ３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => '税務会計能力検定２級（税務会計検定） ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ビジネス能力検定（Ｂ検）２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'マーケティング・ビジネス実務検定 Ｃ級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '45', 'rank' => 'C' ]);
        Card::create([ 'name' => 'DCプランナー２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '44', 'rank' => 'C' ]);
        Card::create([ 'name' => '商業経済検定試験 １級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '44', 'rank' => 'C' ]);
        Card::create([ 'name' => '会計ソフト実務能力試験 ２級（旧財務会計主任者) ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ビジネスキャリア検定 ３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => '准ＰＲプランナー ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => '全経計算実務能力検定試験 ３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '43', 'rank' => 'C' ]);
        Card::create([ 'name' => '認定 BCM-RM(事業継続経営リスクマネジャー)資格', 'description' => '', 'type' => 'ビジネス関連', 'power' => '42', 'rank' => 'C' ]);
        Card::create([ 'name' => 'ビジネス会計検定 ３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '41', 'rank' => 'C' ]);
        Card::create([ 'name' => 'シニアリスクコンサルタント ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '41', 'rank' => 'C' ]);
        Card::create([ 'name' => '変額保険販売資格試験 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '41', 'rank' => 'C' ]);
        Card::create([ 'name' => 'コンピュータ会計能力検定 ２級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '40', 'rank' => 'C' ]);
        Card::create([ 'name' => '商業経済検定試験 ３級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => 'ビジネス能力検定(B検) ３級  ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => 'ＰＲプランナー補 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '38', 'rank' => 'D' ]);
        Card::create([ 'name' => 'ファイナンシャル・プランニング技能士３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '37', 'rank' => 'D' ]);
        Card::create([ 'name' => '販売士３級 ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '37', 'rank' => 'D' ]);
        Card::create([ 'name' => '損害保険募集人一般試験    ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '36', 'rank' => 'D' ]);
        Card::create([ 'name' => '住宅ローンアドバイザー      ', 'description' => '', 'type' => 'ビジネス関連', 'power' => '36', 'rank' => 'D' ]);
    }
}
