name: Laravel Sail CI

on:
  push:
    branches: [ main,ci ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: 'mysql/mysql-server:8.0'
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, session
        coverage: none
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Update .env for CI
      run: |
        cat > .env << EOF
        APP_NAME=Laravel
        APP_ENV=testing
        APP_KEY=
        APP_DEBUG=true
        APP_URL=http://localhost

        LOG_CHANNEL=stack
        LOG_LEVEL=debug

        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3307
        DB_DATABASE=laravel
        DB_USERNAME=sail
        DB_PASSWORD=password

        BROADCAST_DRIVER=log
        CACHE_DRIVER=array
        FILESYSTEM_DISK=local
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=array
        SESSION_LIFETIME=120

        MAIL_MAILER=array

        VITE_APP_NAME="Laravel"
        EOF

    - name: Generate key
      run: php artisan key:generate

    - name: Clear Configuration Cache
      run: |
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install NPM Dependencies
      run: |
        npm ci
        npm install -D @vitejs/plugin-react @inertiajs/react
        npm install -D tailwindcss postcss autoprefixer

    - name: Build Vite Assets
      run: |
        npm run build
      env:
        VITE_APP_NAME: "Laravel"

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P3307 --silent -usail -ppassword; do
          sleep 1
        done

    - name: Create Database
      run: |
        mysql -h127.0.0.1 -P3307 -usail -ppassword -e "CREATE DATABASE IF NOT EXISTS laravel;"

    - name: Run Database Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3307
        DB_DATABASE: laravel
        DB_USERNAME: sail
        DB_PASSWORD: password
      run: php artisan migrate:fresh --force

    - name: Run Laravel Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3307
        DB_DATABASE: laravel
        DB_USERNAME: sail
        DB_PASSWORD: password
        APP_ENV: testing
        SESSION_DRIVER: array
        CACHE_DRIVER: array
        MAIL_MAILER: array
        BCRYPT_ROUNDS: 4
      run: php artisan test --env=testing

